name: CI with Cache workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ runner.os }}/cache-demo
          key: cache-27f9a2c

      - name: prime-cache-27f9a2c
        run: echo "Cache result: ${{ steps.cache.outputs.cache-hit }}"
